### ISSUE TITLE
Is this project still being maintained? - Yes, it is! 🙂👍

### ISSUE THREAD

**Issue by Pomax** [bikeshedder/django-composite-field#1]
I noticed there are no tags on this repo for all releases to date, and there are zero issues, so I was curious whether this is still maintained or whether it was a good idea at the time that's no longer relevant/worked on.

**Comment by bikeshedder** [comment]
This project was recently moved from my Bitbucket account to GitHub.

When moving the repository I forgot to push the tags. I just pushed them.

It is still being developed and I consider it pretty much stable.
I haven't found the need to change a lot except for the occasional fixes for new Django versions.

**Comment by bikeshedder** [comment]
I just fixed the CI tests so this project should now look a bit less dead again.

**Comment by Pomax** [comment]
nice! cheers

**Comment by jleclanche** [comment]
@bikeshedder I see no commits in two years which makes me think it's unmaintained (at the very least a version bump to signal compatibility with recent django would be good!).

If you're having trouble maintaining it, may I suggest [Jazzband](https://jazzband.co/), or [the Code Shelter](https://codeshelter.co/), to reduce the bus factor? :)

**Comment by bikeshedder** [comment]
I didn't see the need to make a new release as all recent releases of Django are supported without the need for any code changes. Due to the way `django-composite-field` works a change is only ever required if some Django internals require a field to add yet another property.

I've just added it to the Code Shelter. :+1:
