### ISSUE TITLE
help_text (and other keyword arguments) missing

### ISSUE THREAD

**Issue by nerdoc** [bikeshedder/django-composite-field#5]
Hi, I try to create a simple CompositeField:

```python
class PeriodField(CompositeField)
    start=models.DateTimeField()
    end=models.DateTimeField()
```
and use it somewhere...
```python

class MyModel(models.Model):
    period = PeriodField(help_text="fooo")
```
And it prints an error:
```
    period = PeriodField(
TypeError: __init__() got an unexpected keyword argument 'help_text'
```

I saw in your [Changelog](https://django-composite-field.readthedocs.io/en/latest/changelog.html?highlight=help_text#version-0-7-6-2016-07-01), that you seemed to implement this at some point of time, is that gone again?

can't I add help_text etc. to a composite field, like `blank`/`null`?

**Comment by nerdoc** [comment]
Ah, you have an example in [ComplexField](https://github.com/bikeshedder/django-composite-field/blob/master/composite_field/complex.py) for that - using an `__init__.py` and distributing the keywords manually. True?

**Comment by bikeshedder** [comment]
That's correct.

That changelog is a bit misleading as it only applies to the `LocalizedField` which does indeed support `help_text`.

That `help_text` is not supported because a `CompositeField` is no real field but creates other fields under the hood. Therefore things like `blank`, `null`, `help_text`, etc. are highly application specific. Just distributing them would be incorrect most of the time.

e.g. in my own projects I quite often have composite fields which consist of many fields. Some are always `blank=True` and others can be configured by passing a `blank` attribute to the `CompositeField`.

**Comment by nerdoc** [comment]
Ok, thanks... also for that GREAT piece of software. Maybe you could add that into the docs? - I can try a PR if you want.

**Comment by nerdoc** [comment]
Ah, I came across my real-world task and now I can formulate my question better - because there is still an issue maybe.
I have a `QuantityField`:
```python
class QuantityField(CompositeField):
    value = models.DecimalField(max_length=1, decimal_places=1)
    unit = CharField()

    def __init__(
        self,
        max_digits: int,
        decimal_places: int,
    )
        super().__init__()
        self["value"].decimal_places = decimal_places
        self["value"].max_digits = max_digits
```
In your ComplexField example linked above you are using `FloatField` which has no mandatory arguments.
In the case of `DecimalField` you have to provide `decimal_places` and `max_digits` at the **declaration**, so it is determined at declaration of the QuantityField (inside) how many decimal_places and max_digits it has. There is no chance of letting the user decide at time of using that QuantityField how many decimal places that model field should have.

Is that right? Wouldn't this be a needed feature?

**Comment by nerdoc** [comment]
WorksForMe with __init__ and passing of parameters down to the real fields. Thanks.
