### ISSUE TITLE
Add __gt__ comparison

### ISSUE THREAD

**Issue by MichaelKim0407** [bikeshedder/django-composite-field#8]
Django's `Field` implements `__eq__` and `__lt__`, which allows fields to be sorted.

`CompositeField` also implements `__eq__` and `__lt__`.
However, this does not guarantee that a list containing `Field`s and `CompositeField`s can be sorted.
This is because `Field.__lt__` is only aware of `Field` but not `CompositeField`, which means `Field() < CompositeField()` returns `NotImplemented`.
To fix this issue, `CompositeField` needs to tell Python how to do `Field() < CompositeField()` by implementing `__gt__`.

**Comment by MichaelKim0407** [comment]
I'm happy to make a quick PR if you can publish an update.

**Comment by bikeshedder** [comment]
Sure. A PR would be highly appreciated.

I'm still maintaining this package. I'm happy to release a new version with your patch. :+1:
